package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name="activity"
    ,catalog="provdmtest"
)
public class Activity  implements java.io.Serializable {


     private String idactivity;
     private Set<Commitactivity> commitactivities = new HashSet<Commitactivity>(0);
     private Set<Testingsuiteexecution> testingsuiteexecutions = new HashSet<Testingsuiteexecution>(0);
     private Set<Buildexecution> buildexecutions = new HashSet<Buildexecution>(0);

    public Activity() {
    }

	
    public Activity(String idactivity) {
        this.idactivity = idactivity;
    }
    public Activity(String idactivity, Set<Commitactivity> commitactivities, Set<Testingsuiteexecution> testingsuiteexecutions, Set<Buildexecution> buildexecutions) {
       this.idactivity = idactivity;
       this.commitactivities = commitactivities;
       this.testingsuiteexecutions = testingsuiteexecutions;
       this.buildexecutions = buildexecutions;
    }
   
     @Id 

    
    @Column(name="idactivity", unique=true, nullable=false, length=45)
    public String getIdactivity() {
        return this.idactivity;
    }
    
    public void setIdactivity(String idactivity) {
        this.idactivity = idactivity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="activity")
    public Set<Commitactivity> getCommitactivities() {
        return this.commitactivities;
    }
    
    public void setCommitactivities(Set<Commitactivity> commitactivities) {
        this.commitactivities = commitactivities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="activity")
    public Set<Testingsuiteexecution> getTestingsuiteexecutions() {
        return this.testingsuiteexecutions;
    }
    
    public void setTestingsuiteexecutions(Set<Testingsuiteexecution> testingsuiteexecutions) {
        this.testingsuiteexecutions = testingsuiteexecutions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="activity")
    public Set<Buildexecution> getBuildexecutions() {
        return this.buildexecutions;
    }
    
    public void setBuildexecutions(Set<Buildexecution> buildexecutions) {
        this.buildexecutions = buildexecutions;
    }




}


