package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Buildexecution generated by hbm2java
 */
@Entity
@Table(name="buildexecution"
    ,catalog="provdmtest"
)
public class Buildexecution  implements java.io.Serializable {


     private String idbuildExecution;
     private Activity activity;
     private String result;
     private Integer duration;
     private String workspace;
     private Set<Wasassociatedwith> wasassociatedwiths = new HashSet<Wasassociatedwith>(0);
     private Set<Wasgeneratedby> wasgeneratedbies = new HashSet<Wasgeneratedby>(0);
     private Set<Hasenvironment> hasenvironments = new HashSet<Hasenvironment>(0);
     private Set<Used> useds = new HashSet<Used>(0);

    public Buildexecution() {
    }

	
    public Buildexecution(String idbuildExecution, Activity activity) {
        this.idbuildExecution = idbuildExecution;
        this.activity = activity;
    }
    public Buildexecution(String idbuildExecution, Activity activity, String result, Integer duration, String workspace, Set<Wasassociatedwith> wasassociatedwiths, Set<Wasgeneratedby> wasgeneratedbies, Set<Hasenvironment> hasenvironments, Set<Used> useds) {
       this.idbuildExecution = idbuildExecution;
       this.activity = activity;
       this.result = result;
       this.duration = duration;
       this.workspace = workspace;
       this.wasassociatedwiths = wasassociatedwiths;
       this.wasgeneratedbies = wasgeneratedbies;
       this.hasenvironments = hasenvironments;
       this.useds = useds;
    }
    
    public Buildexecution(String idbuildExecution, Activity activity, String result, Integer duration, String workspace) {
       this.idbuildExecution = idbuildExecution;
       this.activity = activity;
       this.result = result;
       this.duration = duration;
       this.workspace = workspace;
    }
   
     @Id 

    
    @Column(name="idbuildExecution", unique=true, nullable=false, length=45)
    public String getIdbuildExecution() {
        return this.idbuildExecution;
    }
    
    public void setIdbuildExecution(String idbuildExecution) {
        this.idbuildExecution = idbuildExecution;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="activity_idactivity", nullable=false)
    public Activity getActivity() {
        return this.activity;
    }
    
    public void setActivity(Activity activity) {
        this.activity = activity;
    }

    
    @Column(name="result", length=10)
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }

    
    @Column(name="duration")
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    
    @Column(name="workspace", length=150)
    public String getWorkspace() {
        return this.workspace;
    }
    
    public void setWorkspace(String workspace) {
        this.workspace = workspace;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buildexecution")
    public Set<Wasassociatedwith> getWasassociatedwiths() {
        return this.wasassociatedwiths;
    }
    
    public void setWasassociatedwiths(Set<Wasassociatedwith> wasassociatedwiths) {
        this.wasassociatedwiths = wasassociatedwiths;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buildexecution")
    public Set<Wasgeneratedby> getWasgeneratedbies() {
        return this.wasgeneratedbies;
    }
    
    public void setWasgeneratedbies(Set<Wasgeneratedby> wasgeneratedbies) {
        this.wasgeneratedbies = wasgeneratedbies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buildexecution")
    public Set<Hasenvironment> getHasenvironments() {
        return this.hasenvironments;
    }
    
    public void setHasenvironments(Set<Hasenvironment> hasenvironments) {
        this.hasenvironments = hasenvironments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buildexecution")
    public Set<Used> getUseds() {
        return this.useds;
    }
    
    public void setUseds(Set<Used> useds) {
        this.useds = useds;
    }




}


