package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Composedof generated by hbm2java
 */
@Entity
@Table(name="composedof"
    ,catalog="provdmtest"
)
public class Composedof  implements java.io.Serializable {


     private Integer idcomposedOf;
     private Testingsourcecode testingsourcecode;
     private Testingsuite testingsuite;

    public Composedof() {
    }

    public Composedof(Testingsourcecode testingsourcecode, Testingsuite testingsuite) {
       this.testingsourcecode = testingsourcecode;
       this.testingsuite = testingsuite;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcomposedOF", unique=true, nullable=false)
    public Integer getIdcomposedOf() {
        return this.idcomposedOf;
    }
    
    public void setIdcomposedOf(Integer idcomposedOf) {
        this.idcomposedOf = idcomposedOf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testingSourceCode_idtestingSourceCode", nullable=false)
    public Testingsourcecode getTestingsourcecode() {
        return this.testingsourcecode;
    }
    
    public void setTestingsourcecode(Testingsourcecode testingsourcecode) {
        this.testingsourcecode = testingsourcecode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testingSuite_idtestingSuite", nullable=false)
    public Testingsuite getTestingsuite() {
        return this.testingsuite;
    }
    
    public void setTestingsuite(Testingsuite testingsuite) {
        this.testingsuite = testingsuite;
    }




}


