package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Covers generated by hbm2java
 */
@Entity
@Table(name="covers"
    ,catalog="provdmtest"
)
public class Covers  implements java.io.Serializable {


     private Integer idcovers;
     private Sourcecode sourcecode;
     private Testingmethod testingmethod;

    public Covers() {
    }

    public Covers(Sourcecode sourcecode, Testingmethod testingmethod) {
       this.sourcecode = sourcecode;
       this.testingmethod = testingmethod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcovers", unique=true, nullable=false)
    public Integer getIdcovers() {
        return this.idcovers;
    }
    
    public void setIdcovers(Integer idcovers) {
        this.idcovers = idcovers;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sourceCode_idsourceCode", nullable=false)
    public Sourcecode getSourcecode() {
        return this.sourcecode;
    }
    
    public void setSourcecode(Sourcecode sourcecode) {
        this.sourcecode = sourcecode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testingMethod_idtestingMethod", nullable=false)
    public Testingmethod getTestingmethod() {
        return this.testingmethod;
    }
    
    public void setTestingmethod(Testingmethod testingmethod) {
        this.testingmethod = testingmethod;
    }




}


