package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Environment generated by hbm2java
 */
@Entity
@Table(name="environment"
    ,catalog="provdmtest"
)
public class Environment  implements java.io.Serializable {


     private String idenvironment;
     private Project project;
     private String javaClassversion;
     private String javaRuntimeName;
     private String javaRuntimeVersion;
     private String javaSpecificationName;
     private String javaVmSpecificationVersion;
     private String javaVmVersion;
     private String osName;
     private String osVersion;
     private Integer idBuild;
     private Set<Hasenvironment> hasenvironments = new HashSet<Hasenvironment>(0);

    public Environment() {
    }

	
    public Environment(String idenvironment, Project project) {
        this.idenvironment = idenvironment;
        this.project = project;
    }
    public Environment(String idenvironment, Project project, String javaClassversion, String javaRuntimeName, String javaRuntimeVersion, String javaSpecificationName, String javaVmSpecificationVersion, String javaVmVersion, String osName, String osVersion, Integer idBuild, Set<Hasenvironment> hasenvironments) {
       this.idenvironment = idenvironment;
       this.project = project;
       this.javaClassversion = javaClassversion;
       this.javaRuntimeName = javaRuntimeName;
       this.javaRuntimeVersion = javaRuntimeVersion;
       this.javaSpecificationName = javaSpecificationName;
       this.javaVmSpecificationVersion = javaVmSpecificationVersion;
       this.javaVmVersion = javaVmVersion;
       this.osName = osName;
       this.osVersion = osVersion;
       this.idBuild = idBuild;
       this.hasenvironments = hasenvironments;
    }
   
     @Id 

    
    @Column(name="idenvironment", unique=true, nullable=false, length=45)
    public String getIdenvironment() {
        return this.idenvironment;
    }
    
    public void setIdenvironment(String idenvironment) {
        this.idenvironment = idenvironment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_idproject", nullable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    
    @Column(name="javaClassversion", length=45)
    public String getJavaClassversion() {
        return this.javaClassversion;
    }
    
    public void setJavaClassversion(String javaClassversion) {
        this.javaClassversion = javaClassversion;
    }

    
    @Column(name="javaRuntimeName", length=45)
    public String getJavaRuntimeName() {
        return this.javaRuntimeName;
    }
    
    public void setJavaRuntimeName(String javaRuntimeName) {
        this.javaRuntimeName = javaRuntimeName;
    }

    
    @Column(name="javaRuntimeVersion", length=45)
    public String getJavaRuntimeVersion() {
        return this.javaRuntimeVersion;
    }
    
    public void setJavaRuntimeVersion(String javaRuntimeVersion) {
        this.javaRuntimeVersion = javaRuntimeVersion;
    }

    
    @Column(name="javaSpecificationName", length=45)
    public String getJavaSpecificationName() {
        return this.javaSpecificationName;
    }
    
    public void setJavaSpecificationName(String javaSpecificationName) {
        this.javaSpecificationName = javaSpecificationName;
    }

    
    @Column(name="javaVmSpecificationVersion", length=45)
    public String getJavaVmSpecificationVersion() {
        return this.javaVmSpecificationVersion;
    }
    
    public void setJavaVmSpecificationVersion(String javaVmSpecificationVersion) {
        this.javaVmSpecificationVersion = javaVmSpecificationVersion;
    }

    
    @Column(name="javaVmVersion", length=45)
    public String getJavaVmVersion() {
        return this.javaVmVersion;
    }
    
    public void setJavaVmVersion(String javaVmVersion) {
        this.javaVmVersion = javaVmVersion;
    }

    
    @Column(name="osName", length=45)
    public String getOsName() {
        return this.osName;
    }
    
    public void setOsName(String osName) {
        this.osName = osName;
    }

    
    @Column(name="osVersion", length=45)
    public String getOsVersion() {
        return this.osVersion;
    }
    
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }

    
    @Column(name="idBuild")
    public Integer getIdBuild() {
        return this.idBuild;
    }
    
    public void setIdBuild(Integer idBuild) {
        this.idBuild = idBuild;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="environment")
    public Set<Hasenvironment> getHasenvironments() {
        return this.hasenvironments;
    }
    
    public void setHasenvironments(Set<Hasenvironment> hasenvironments) {
        this.hasenvironments = hasenvironments;
    }




}


