package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,catalog="provdmtest"
)
public class Person  implements java.io.Serializable {


     private String idperson;
     private Agent agent;
     private String name;
     private Set<Wasassociatedwith> wasassociatedwiths = new HashSet<Wasassociatedwith>(0);
     private Set<Wasattributedto> wasattributedtos = new HashSet<Wasattributedto>(0);

    public Person() {
    }

	
    public Person(String idperson, Agent agent) {
        this.idperson = idperson;
        this.agent = agent;
    }
    public Person(String idperson, Agent agent, String name, Set<Wasassociatedwith> wasassociatedwiths, Set<Wasattributedto> wasattributedtos) {
       this.idperson = idperson;
       this.agent = agent;
       this.name = name;
       this.wasassociatedwiths = wasassociatedwiths;
       this.wasattributedtos = wasattributedtos;
    }
   
     @Id 

    
    @Column(name="idperson", unique=true, nullable=false, length=45)
    public String getIdperson() {
        return this.idperson;
    }
    
    public void setIdperson(String idperson) {
        this.idperson = idperson;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="agent_idagent", nullable=false)
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set<Wasassociatedwith> getWasassociatedwiths() {
        return this.wasassociatedwiths;
    }
    
    public void setWasassociatedwiths(Set<Wasassociatedwith> wasassociatedwiths) {
        this.wasassociatedwiths = wasassociatedwiths;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
    public Set<Wasattributedto> getWasattributedtos() {
        return this.wasattributedtos;
    }
    
    public void setWasattributedtos(Set<Wasattributedto> wasattributedtos) {
        this.wasattributedtos = wasattributedtos;
    }




}


