package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name="project"
    ,catalog="provdmtest"
)
public class Project  implements java.io.Serializable {


     private String idproject;
     private Entityprov entityprov;
     private String name;
     private String projectVersion;
     private Set<Wasattributedto> wasattributedtos = new HashSet<Wasattributedto>(0);
     private Set<Testingartifact> testingartifacts = new HashSet<Testingartifact>(0);
     private Set<Environment> environments = new HashSet<Environment>(0);
     private Set<Testingsuite> testingsuites = new HashSet<Testingsuite>(0);
     private Set<Softwareartifact> softwareartifacts = new HashSet<Softwareartifact>(0);

    public Project() {
    }

	
    public Project(String idproject, Entityprov entityprov) {
        this.idproject = idproject;
        this.entityprov = entityprov;
    }
    public Project(String idproject, Entityprov entityprov, String name, String projectVersion, Set<Wasattributedto> wasattributedtos, Set<Testingartifact> testingartifacts, Set<Environment> environments, Set<Testingsuite> testingsuites, Set<Softwareartifact> softwareartifacts) {
       this.idproject = idproject;
       this.entityprov = entityprov;
       this.name = name;
       this.projectVersion = projectVersion;
       this.wasattributedtos = wasattributedtos;
       this.testingartifacts = testingartifacts;
       this.environments = environments;
       this.testingsuites = testingsuites;
       this.softwareartifacts = softwareartifacts;
    }
   
     @Id 

    
    @Column(name="idproject", unique=true, nullable=false, length=45)
    public String getIdproject() {
        return this.idproject;
    }
    
    public void setIdproject(String idproject) {
        this.idproject = idproject;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entity_identity", nullable=false)
    public Entityprov getEntityprov() {
        return this.entityprov;
    }
    
    public void setEntityprov(Entityprov entityprov) {
        this.entityprov = entityprov;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="project_version", length=45)
    public String getProjectVersion() {
        return this.projectVersion;
    }
    
    public void setProjectVersion(String projectVersion) {
        this.projectVersion = projectVersion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="project")
    public Set<Wasattributedto> getWasattributedtos() {
        return this.wasattributedtos;
    }
    
    public void setWasattributedtos(Set<Wasattributedto> wasattributedtos) {
        this.wasattributedtos = wasattributedtos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="project")
    public Set<Testingartifact> getTestingartifacts() {
        return this.testingartifacts;
    }
    
    public void setTestingartifacts(Set<Testingartifact> testingartifacts) {
        this.testingartifacts = testingartifacts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="project")
    public Set<Environment> getEnvironments() {
        return this.environments;
    }
    
    public void setEnvironments(Set<Environment> environments) {
        this.environments = environments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="project")
    public Set<Testingsuite> getTestingsuites() {
        return this.testingsuites;
    }
    
    public void setTestingsuites(Set<Testingsuite> testingsuites) {
        this.testingsuites = testingsuites;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="project")
    public Set<Softwareartifact> getSoftwareartifacts() {
        return this.softwareartifacts;
    }
    
    public void setSoftwareartifacts(Set<Softwareartifact> softwareartifacts) {
        this.softwareartifacts = softwareartifacts;
    }




}


