package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Softwarebuild generated by hbm2java
 */
@Entity
@Table(name="softwarebuild"
    ,catalog="provdmtest"
)
public class Softwarebuild  implements java.io.Serializable {


     private String idsoftwareBuild;
     private Softwareartifact softwareartifact;
     private String startBuild;
     private Double durationBuild;
     private Set<Wasderivedfrom> wasderivedfroms = new HashSet<Wasderivedfrom>(0);
     private Set<Wasgeneratedby> wasgeneratedbies = new HashSet<Wasgeneratedby>(0);

    public Softwarebuild() {
    }

	
    public Softwarebuild(String idsoftwareBuild, Softwareartifact softwareartifact) {
        this.idsoftwareBuild = idsoftwareBuild;
        this.softwareartifact = softwareartifact;
    }
    public Softwarebuild(String idsoftwareBuild, Softwareartifact softwareartifact, String startBuild, Double durationBuild, Set<Wasderivedfrom> wasderivedfroms, Set<Wasgeneratedby> wasgeneratedbies) {
       this.idsoftwareBuild = idsoftwareBuild;
       this.softwareartifact = softwareartifact;
       this.startBuild = startBuild;
       this.durationBuild = durationBuild;
       this.wasderivedfroms = wasderivedfroms;
       this.wasgeneratedbies = wasgeneratedbies;
    }
    
    public Softwarebuild(String idsoftwareBuild, Softwareartifact softwareartifact, String startBuild, Double durationBuild) {
       this.idsoftwareBuild = idsoftwareBuild;
       this.softwareartifact = softwareartifact;
       this.startBuild = startBuild;
       this.durationBuild = durationBuild;
    }
   
   
     @Id 

    
    @Column(name="idsoftwareBuild", unique=true, nullable=false, length=45)
    public String getIdsoftwareBuild() {
        return this.idsoftwareBuild;
    }
    
    public void setIdsoftwareBuild(String idsoftwareBuild) {
        this.idsoftwareBuild = idsoftwareBuild;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="softwareArtifact_idsoftwareArtifact", nullable=false)
    public Softwareartifact getSoftwareartifact() {
        return this.softwareartifact;
    }
    
    public void setSoftwareartifact(Softwareartifact softwareartifact) {
        this.softwareartifact = softwareartifact;
    }

    
    @Column(name="startBuild", length=45)
    public String getStartBuild() {
        return this.startBuild;
    }
    
    public void setStartBuild(String startBuild) {
        this.startBuild = startBuild;
    }

    
    @Column(name="durationBuild", precision=22, scale=0)
    public Double getDurationBuild() {
        return this.durationBuild;
    }
    
    public void setDurationBuild(Double durationBuild) {
        this.durationBuild = durationBuild;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwarebuild")
    public Set<Wasderivedfrom> getWasderivedfroms() {
        return this.wasderivedfroms;
    }
    
    public void setWasderivedfroms(Set<Wasderivedfrom> wasderivedfroms) {
        this.wasderivedfroms = wasderivedfroms;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwarebuild")
    public Set<Wasgeneratedby> getWasgeneratedbies() {
        return this.wasgeneratedbies;
    }
    
    public void setWasgeneratedbies(Set<Wasgeneratedby> wasgeneratedbies) {
        this.wasgeneratedbies = wasgeneratedbies;
    }




}


