package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Softwareartifact generated by hbm2java
 */
@Entity
@Table(name="softwareartifact"
    ,catalog="provdmtest"
)
public class Softwareartifact  implements java.io.Serializable {


     private String idsoftwareArtifact;
     private Project project;
     private Set<Softwarebuild> softwarebuilds = new HashSet<Softwarebuild>(0);
     private Set<Sourcecode> sourcecodes = new HashSet<Sourcecode>(0);
     private Set<Wasderivedfrom> wasderivedfroms = new HashSet<Wasderivedfrom>(0);
     private Set<Softwareexecutable> softwareexecutables = new HashSet<Softwareexecutable>(0);
     private Set<Used> useds = new HashSet<Used>(0);

    public Softwareartifact() {
    }

	
    public Softwareartifact(String idsoftwareArtifact, Project project) {
        this.idsoftwareArtifact = idsoftwareArtifact;
        this.project = project;
    }
    public Softwareartifact(String idsoftwareArtifact, Project project, Set<Softwarebuild> softwarebuilds, Set<Sourcecode> sourcecodes, Set<Wasderivedfrom> wasderivedfroms, Set<Softwareexecutable> softwareexecutables, Set<Used> useds) {
       this.idsoftwareArtifact = idsoftwareArtifact;
       this.project = project;
       this.softwarebuilds = softwarebuilds;
       this.sourcecodes = sourcecodes;
       this.wasderivedfroms = wasderivedfroms;
       this.softwareexecutables = softwareexecutables;
       this.useds = useds;
    }
   
     @Id 

    
    @Column(name="idsoftwareArtifact", unique=true, nullable=false, length=45)
    public String getIdsoftwareArtifact() {
        return this.idsoftwareArtifact;
    }
    
    public void setIdsoftwareArtifact(String idsoftwareArtifact) {
        this.idsoftwareArtifact = idsoftwareArtifact;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_idproject", nullable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwareartifact")
    public Set<Softwarebuild> getSoftwarebuilds() {
        return this.softwarebuilds;
    }
    
    public void setSoftwarebuilds(Set<Softwarebuild> softwarebuilds) {
        this.softwarebuilds = softwarebuilds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwareartifact")
    public Set<Sourcecode> getSourcecodes() {
        return this.sourcecodes;
    }
    
    public void setSourcecodes(Set<Sourcecode> sourcecodes) {
        this.sourcecodes = sourcecodes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwareartifact")
    public Set<Wasderivedfrom> getWasderivedfroms() {
        return this.wasderivedfroms;
    }
    
    public void setWasderivedfroms(Set<Wasderivedfrom> wasderivedfroms) {
        this.wasderivedfroms = wasderivedfroms;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwareartifact")
    public Set<Softwareexecutable> getSoftwareexecutables() {
        return this.softwareexecutables;
    }
    
    public void setSoftwareexecutables(Set<Softwareexecutable> softwareexecutables) {
        this.softwareexecutables = softwareexecutables;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="softwareartifact")
    public Set<Used> getUseds() {
        return this.useds;
    }
    
    public void setUseds(Set<Used> useds) {
        this.useds = useds;
    }




}


