package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testingsourcecode generated by hbm2java
 */
@Entity
@Table(name="testingsourcecode"
    ,catalog="provdmtest"
)
public class Testingsourcecode  implements java.io.Serializable {


     private int idtestingSourceCode;
     private Testingartifact testingartifact;
     private String name;
     private String path;
     private Set<Wasderivedfrom> wasderivedfroms = new HashSet<Wasderivedfrom>(0);
     private Set<Composedof> composedofs = new HashSet<Composedof>(0);

    public Testingsourcecode() {
    }

	
    public Testingsourcecode(int idtestingSourceCode, Testingartifact testingartifact) {
        this.idtestingSourceCode = idtestingSourceCode;
        this.testingartifact = testingartifact;
    }
    public Testingsourcecode(int idtestingSourceCode, Testingartifact testingartifact, String name, String path, Set<Wasderivedfrom> wasderivedfroms, Set<Composedof> composedofs) {
       this.idtestingSourceCode = idtestingSourceCode;
       this.testingartifact = testingartifact;
       this.name = name;
       this.path = path;
       this.wasderivedfroms = wasderivedfroms;
       this.composedofs = composedofs;
    }
    
    public Testingsourcecode(Testingartifact testingartifact, String name, String path) {
       this.testingartifact = testingartifact;
       this.name = name;
       this.path = path;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idtestingSourceCode", unique=true, nullable=false)
    public int getIdtestingSourceCode() {
        return this.idtestingSourceCode;
    }
    
    public void setIdtestingSourceCode(int idtestingSourceCode) {
        this.idtestingSourceCode = idtestingSourceCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testingArtifact_idtestingArtifact", nullable=false)
    public Testingartifact getTestingartifact() {
        return this.testingartifact;
    }
    
    public void setTestingartifact(Testingartifact testingartifact) {
        this.testingartifact = testingartifact;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="path", length=300)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testingsourcecode")
    public Set<Wasderivedfrom> getWasderivedfroms() {
        return this.wasderivedfroms;
    }
    
    public void setWasderivedfroms(Set<Wasderivedfrom> wasderivedfroms) {
        this.wasderivedfroms = wasderivedfroms;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testingsourcecode")
    public Set<Composedof> getComposedofs() {
        return this.composedofs;
    }
    
    public void setComposedofs(Set<Composedof> composedofs) {
        this.composedofs = composedofs;
    }




}


