package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testingmethodexecution generated by hbm2java
 */
@Entity
@Table(name="testingmethodexecution"
    ,catalog="provdmtest"
)
public class Testingmethodexecution  implements java.io.Serializable {


     private Integer idtestingMethodExection;
     private Testingclassexecution testingclassexecution;
     private Testingmethod testingmethod;
     private Float durationTime;
     private String result;
     private String errorDatails;
     private String errorStrackTrace;
     private Set<Wasinformedby> wasinformedbies = new HashSet<Wasinformedby>(0);
     private Set<Used> useds = new HashSet<Used>(0);

    public Testingmethodexecution() {
    }

	
    public Testingmethodexecution(Testingclassexecution testingclassexecution, Testingmethod testingmethod) {
        this.testingclassexecution = testingclassexecution;
        this.testingmethod = testingmethod;
    }
    public Testingmethodexecution(Testingclassexecution testingclassexecution, Testingmethod testingmethod, Float durationTime, String result, String errorDatails, String errorStrackTrace, Set<Wasinformedby> wasinformedbies, Set<Used> useds) {
       this.testingclassexecution = testingclassexecution;
       this.testingmethod = testingmethod;
       this.durationTime = durationTime;
       this.result = result;
       this.errorDatails = errorDatails;
       this.errorStrackTrace = errorStrackTrace;
       this.wasinformedbies = wasinformedbies;
       this.useds = useds;
    }
    
    public Testingmethodexecution(Testingclassexecution testingclassexecution, Testingmethod testingmethod, Float durationTime, String result, String errorDatails, String errorStrackTrace) {
       this.testingclassexecution = testingclassexecution;
       this.testingmethod = testingmethod;
       this.durationTime = durationTime;
       this.result = result;
       this.errorDatails = errorDatails;
       this.errorStrackTrace = errorStrackTrace;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="idtestingMethodExection", unique=true, nullable=false)
    public Integer getIdtestingMethodExection() {
        return this.idtestingMethodExection;
    }
    
    public void setIdtestingMethodExection(Integer idtestingMethodExection) {
        this.idtestingMethodExection = idtestingMethodExection;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testingClassExecution_idtestingClassExecution", nullable=false)
    public Testingclassexecution getTestingclassexecution() {
        return this.testingclassexecution;
    }
    
    public void setTestingclassexecution(Testingclassexecution testingclassexecution) {
        this.testingclassexecution = testingclassexecution;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testingMethod_idtestingMethod", nullable=false)
    public Testingmethod getTestingmethod() {
        return this.testingmethod;
    }
    
    public void setTestingmethod(Testingmethod testingmethod) {
        this.testingmethod = testingmethod;
    }

    
    @Column(name="durationTime", precision=12, scale=0)
    public Float getDurationTime() {
        return this.durationTime;
    }
    
    public void setDurationTime(Float durationTime) {
        this.durationTime = durationTime;
    }

    
    @Column(name="result", length=45)
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }

    
    @Column(name="errorDatails", length=150)
    public String getErrorDatails() {
        return this.errorDatails;
    }
    
    public void setErrorDatails(String errorDatails) {
        this.errorDatails = errorDatails;
    }

    
    @Column(name="errorStrackTrace", length=150)
    public String getErrorStrackTrace() {
        return this.errorStrackTrace;
    }
    
    public void setErrorStrackTrace(String errorStrackTrace) {
        this.errorStrackTrace = errorStrackTrace;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testingmethodexecution")
    public Set<Wasinformedby> getWasinformedbies() {
        return this.wasinformedbies;
    }
    
    public void setWasinformedbies(Set<Wasinformedby> wasinformedbies) {
        this.wasinformedbies = wasinformedbies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testingmethodexecution")
    public Set<Used> getUseds() {
        return this.useds;
    }
    
    public void setUseds(Set<Used> useds) {
        this.useds = useds;
    }




}


