package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testinglog generated by hbm2java
 */
@Entity
@Table(name="testinglog"
    ,catalog="provdmtest"
)
public class Testinglog  implements java.io.Serializable {


     private String idtestingLog;
     private Testingartifact testingartifact;
     private String path;
     private String generationDateTime;
     private Set<Wasgeneratedby> wasgeneratedbies = new HashSet<Wasgeneratedby>(0);
     private Set<Wasderivedfrom> wasderivedfroms = new HashSet<Wasderivedfrom>(0);

    public Testinglog() {
    }

	
    public Testinglog(String idtestingLog, Testingartifact testingartifact) {
        this.idtestingLog = idtestingLog;
        this.testingartifact = testingartifact;
    }
    public Testinglog(String idtestingLog, Testingartifact testingartifact, String path, String generationDateTime, Set<Wasgeneratedby> wasgeneratedbies, Set<Wasderivedfrom> wasderivedfroms) {
       this.idtestingLog = idtestingLog;
       this.testingartifact = testingartifact;
       this.path = path;
       this.generationDateTime = generationDateTime;
       this.wasgeneratedbies = wasgeneratedbies;
       this.wasderivedfroms = wasderivedfroms;
    }
    
    public Testinglog(String idtestingLog, Testingartifact testingartifact, String path, String generationDateTime) {
       this.idtestingLog = idtestingLog;
       this.testingartifact = testingartifact;
       this.path = path;
       this.generationDateTime = generationDateTime;
    
    }
   
     @Id 

    
    @Column(name="idtestingLog", unique=true, nullable=false, length=45)
    public String getIdtestingLog() {
        return this.idtestingLog;
    }
    
    public void setIdtestingLog(String idtestingLog) {
        this.idtestingLog = idtestingLog;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testingArtifact_idtestingArtifact", nullable=false)
    public Testingartifact getTestingartifact() {
        return this.testingartifact;
    }
    
    public void setTestingartifact(Testingartifact testingartifact) {
        this.testingartifact = testingartifact;
    }

    
    @Column(name="path", length=300)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="generationDateTime", length=45)
    public String getGenerationDateTime() {
        return this.generationDateTime;
    }
    
    public void setGenerationDateTime(String generationDateTime) {
        this.generationDateTime = generationDateTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testinglog")
    public Set<Wasgeneratedby> getWasgeneratedbies() {
        return this.wasgeneratedbies;
    }
    
    public void setWasgeneratedbies(Set<Wasgeneratedby> wasgeneratedbies) {
        this.wasgeneratedbies = wasgeneratedbies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testinglog")
    public Set<Wasderivedfrom> getWasderivedfroms() {
        return this.wasderivedfroms;
    }
    
    public void setWasderivedfroms(Set<Wasderivedfrom> wasderivedfroms) {
        this.wasderivedfroms = wasderivedfroms;
    }




}


