package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Wasattributedto generated by hbm2java
 */
@Entity
@Table(name="wasattributedto"
    ,catalog="provdmtest"
)
public class Wasattributedto  implements java.io.Serializable {


     private Integer idwasAttributedTo;
     private Person person;
     private Project project;

    public Wasattributedto() {
    }

    public Wasattributedto(Person person, Project project) {
       this.person = person;
       this.project = project;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idwasAttributedTo", unique=true, nullable=false)
    public Integer getIdwasAttributedTo() {
        return this.idwasAttributedTo;
    }
    
    public void setIdwasAttributedTo(Integer idwasAttributedTo) {
        this.idwasAttributedTo = idwasAttributedTo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="person_idperson")
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_idproject")
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }




}


