package model;
// Generated 04/07/2017 11:51:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Wasgeneratedby generated by hbm2java
 */
@Entity
@Table(name="wasgeneratedby"
    ,catalog="provdmtest"
)
public class Wasgeneratedby  implements java.io.Serializable {


     private Integer idwasGeneratedBy;
     private Buildexecution buildexecution;
     private Softwarebuild softwarebuild;
     private Softwareexecutable softwareexecutable;
     private Testinglog testinglog;
     private Testingsuiteexecution testingsuiteexecution;

    public Wasgeneratedby() {
    }

    public Wasgeneratedby(Buildexecution buildexecution, Softwarebuild softwarebuild, Softwareexecutable softwareexecutable, Testinglog testinglog, Testingsuiteexecution testingsuiteexecution) {
       this.buildexecution = buildexecution;
       this.softwarebuild = softwarebuild;
       this.softwareexecutable = softwareexecutable;
       this.testinglog = testinglog;
       this.testingsuiteexecution = testingsuiteexecution;
    }
    
    public Wasgeneratedby(Buildexecution buildexecution, Softwarebuild softwarebuild) {
       this.buildexecution = buildexecution;
       this.softwarebuild = softwarebuild;
    }
    
    public Wasgeneratedby(Buildexecution buildexecution, Softwareexecutable softwareexecutable) {
       this.buildexecution = buildexecution;
       this.softwareexecutable = softwareexecutable;
    }
    
    public Wasgeneratedby(Testinglog testinglog, Testingsuiteexecution testingsuiteexecution) {
       this.testinglog = testinglog;
       this.testingsuiteexecution = testingsuiteexecution;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idwasGeneratedBy", unique=true, nullable=false)
    public Integer getIdwasGeneratedBy() {
        return this.idwasGeneratedBy;
    }
    
    public void setIdwasGeneratedBy(Integer idwasGeneratedBy) {
        this.idwasGeneratedBy = idwasGeneratedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="buildExecution_idbuildExecution")
    public Buildexecution getBuildexecution() {
        return this.buildexecution;
    }
    
    public void setBuildexecution(Buildexecution buildexecution) {
        this.buildexecution = buildexecution;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="softwareBuild_idsoftwareBuild")
    public Softwarebuild getSoftwarebuild() {
        return this.softwarebuild;
    }
    
    public void setSoftwarebuild(Softwarebuild softwarebuild) {
        this.softwarebuild = softwarebuild;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="softwareExecutable_idsoftwareExecutable")
    public Softwareexecutable getSoftwareexecutable() {
        return this.softwareexecutable;
    }
    
    public void setSoftwareexecutable(Softwareexecutable softwareexecutable) {
        this.softwareexecutable = softwareexecutable;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testingLog_idtestingLog")
    public Testinglog getTestinglog() {
        return this.testinglog;
    }
    
    public void setTestinglog(Testinglog testinglog) {
        this.testinglog = testinglog;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testingSuiteExecution_idtestingSuiteExecution")
    public Testingsuiteexecution getTestingsuiteexecution() {
        return this.testingsuiteexecution;
    }
    
    public void setTestingsuiteexecution(Testingsuiteexecution testingsuiteexecution) {
        this.testingsuiteexecution = testingsuiteexecution;
    }




}


